//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DianetMob.Properties {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LangResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LangResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DianetMob.Properties.LangResource", typeof(LangResource).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string add {
            get {
                return ResourceManager.GetString("add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add your Info.
        /// </summary>
        internal static string addInfo {
            get {
                return ResourceManager.GetString("addInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Entry To Log.
        /// </summary>
        internal static string addLog {
            get {
                return ResourceManager.GetString("addLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Weight.
        /// </summary>
        internal static string addWeight {
            get {
                return ResourceManager.GetString("addWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to After.
        /// </summary>
        internal static string after {
            get {
                return ResourceManager.GetString("after", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alerts.
        /// </summary>
        internal static string alerts {
            get {
                return ResourceManager.GetString("alerts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already have an account.
        /// </summary>
        internal static string already {
            get {
                return ResourceManager.GetString("already", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Before.
        /// </summary>
        internal static string before {
            get {
                return ResourceManager.GetString("before", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birthday.
        /// </summary>
        internal static string birthday {
            get {
                return ResourceManager.GetString("birthday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Breakfast.
        /// </summary>
        internal static string breakfast {
            get {
                return ResourceManager.GetString("breakfast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Budget.
        /// </summary>
        internal static string budget {
            get {
                return ResourceManager.GetString("budget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buy.
        /// </summary>
        internal static string buy {
            get {
                return ResourceManager.GetString("buy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calories.
        /// </summary>
        internal static string calories {
            get {
                return ResourceManager.GetString("calories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carbohydrates.
        /// </summary>
        internal static string carbohydrates {
            get {
                return ResourceManager.GetString("carbohydrates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password.
        /// </summary>
        internal static string changePsd {
            get {
                return ResourceManager.GetString("changePsd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have changed the measurement unit. Do you want to automatically convert the measurements?.
        /// </summary>
        internal static string changeWeightType {
            get {
                return ResourceManager.GetString("changeWeightType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Measurement unit change.
        /// </summary>
        internal static string changeWeightTypeTitle {
            get {
                return ResourceManager.GetString("changeWeightTypeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check your email.
        /// </summary>
        internal static string checkemail {
            get {
                return ResourceManager.GetString("checkemail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cholesterol.
        /// </summary>
        internal static string cholesterol {
            get {
                return ResourceManager.GetString("cholesterol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to complete your profile.
        /// </summary>
        internal static string completeProfile {
            get {
                return ResourceManager.GetString("completeProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE.
        /// </summary>
        internal static string delete {
            get {
                return ResourceManager.GetString("delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string description {
            get {
                return ResourceManager.GetString("description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fill desired weight.
        /// </summary>
        internal static string desiredweight {
            get {
                return ResourceManager.GetString("desiredweight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detail.
        /// </summary>
        internal static string detail {
            get {
                return ResourceManager.GetString("detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diet type.
        /// </summary>
        internal static string diettype {
            get {
                return ResourceManager.GetString("diettype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dinner.
        /// </summary>
        internal static string dinner {
            get {
                return ResourceManager.GetString("dinner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string edit {
            get {
                return ResourceManager.GetString("edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string email {
            get {
                return ResourceManager.GetString("email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your credentials.
        /// </summary>
        internal static string entercredentials {
            get {
                return ResourceManager.GetString("entercredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your email.
        /// </summary>
        internal static string enterMail {
            get {
                return ResourceManager.GetString("enterMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string error {
            get {
                return ResourceManager.GetString("error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excercise.
        /// </summary>
        internal static string exercise {
            get {
                return ResourceManager.GetString("exercise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exercise time (in minutes).
        /// </summary>
        internal static string exerciseMinutes {
            get {
                return ResourceManager.GetString("exerciseMinutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string exit {
            get {
                return ResourceManager.GetString("exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fats.
        /// </summary>
        internal static string fats {
            get {
                return ResourceManager.GetString("fats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Female.
        /// </summary>
        internal static string female {
            get {
                return ResourceManager.GetString("female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fertility.
        /// </summary>
        internal static string fertility {
            get {
                return ResourceManager.GetString("fertility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fiber.
        /// </summary>
        internal static string fiber {
            get {
                return ResourceManager.GetString("fiber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fill description.
        /// </summary>
        internal static string filldescr {
            get {
                return ResourceManager.GetString("filldescr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill all fields.
        /// </summary>
        internal static string fillfields {
            get {
                return ResourceManager.GetString("fillfields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fill minutes.
        /// </summary>
        internal static string fillmin {
            get {
                return ResourceManager.GetString("fillmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fill name.
        /// </summary>
        internal static string fillname {
            get {
                return ResourceManager.GetString("fillname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fill recurrence.
        /// </summary>
        internal static string fillrecur {
            get {
                return ResourceManager.GetString("fillrecur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fill today&apos;s weight.
        /// </summary>
        internal static string filltoday {
            get {
                return ResourceManager.GetString("filltoday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Food.
        /// </summary>
        internal static string food {
            get {
                return ResourceManager.GetString("food", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string foodname {
            get {
                return ResourceManager.GetString("foodname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot Password?.
        /// </summary>
        internal static string forgotPsd {
            get {
                return ResourceManager.GetString("forgotPsd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender.
        /// </summary>
        internal static string gender {
            get {
                return ResourceManager.GetString("gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong.
        /// </summary>
        internal static string genericerror {
            get {
                return ResourceManager.GetString("genericerror", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goal.
        /// </summary>
        internal static string goal {
            get {
                return ResourceManager.GetString("goal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goal edit.
        /// </summary>
        internal static string goalEdit {
            get {
                return ResourceManager.GetString("goalEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Go to login.
        /// </summary>
        internal static string gotoLogin {
            get {
                return ResourceManager.GetString("gotoLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height type.
        /// </summary>
        internal static string heighttype {
            get {
                return ResourceManager.GetString("heighttype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heigth.
        /// </summary>
        internal static string heigth {
            get {
                return ResourceManager.GetString("heigth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to insert...
        /// </summary>
        internal static string insert {
            get {
                return ResourceManager.GetString("insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert your height..
        /// </summary>
        internal static string insertHeight {
            get {
                return ResourceManager.GetString("insertHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert your weight..
        /// </summary>
        internal static string insertWeight {
            get {
                return ResourceManager.GetString("insertWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert your age..
        /// </summary>
        internal static string insertΑge {
            get {
                return ResourceManager.GetString("insertΑge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter valid email.
        /// </summary>
        internal static string invalidemail {
            get {
                return ResourceManager.GetString("invalidemail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kgs.
        /// </summary>
        internal static string kgs {
            get {
                return ResourceManager.GetString("kgs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string language {
            get {
                return ResourceManager.GetString("language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to or maybe later?.
        /// </summary>
        internal static string later {
            get {
                return ResourceManager.GetString("later", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string login {
            get {
                return ResourceManager.GetString("login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login via Facebook.
        /// </summary>
        internal static string loginFB {
            get {
                return ResourceManager.GetString("loginFB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lunch.
        /// </summary>
        internal static string lunch {
            get {
                return ResourceManager.GetString("lunch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Male.
        /// </summary>
        internal static string male {
            get {
                return ResourceManager.GetString("male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        internal static string message {
            get {
                return ResourceManager.GetString("message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Day.
        /// </summary>
        internal static string myDay {
            get {
                return ResourceManager.GetString("myDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My food.
        /// </summary>
        internal static string myfood {
            get {
                return ResourceManager.GetString("myfood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My food.
        /// </summary>
        internal static string myfoods {
            get {
                return ResourceManager.GetString("myfoods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string name {
            get {
                return ResourceManager.GetString("name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Natrium.
        /// </summary>
        internal static string natrium {
            get {
                return ResourceManager.GetString("natrium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Net.
        /// </summary>
        internal static string net {
            get {
                return ResourceManager.GetString("net", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Password.
        /// </summary>
        internal static string newPsd {
            get {
                return ResourceManager.GetString("newPsd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NK cells.
        /// </summary>
        internal static string nkcells {
            get {
                return ResourceManager.GetString("nkcells", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NO.
        /// </summary>
        internal static string no {
            get {
                return ResourceManager.GetString("no", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No camera available.
        /// </summary>
        internal static string nocamera {
            get {
                return ResourceManager.GetString("nocamera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords not match.
        /// </summary>
        internal static string nomatch {
            get {
                return ResourceManager.GetString("nomatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal.
        /// </summary>
        internal static string normal {
            get {
                return ResourceManager.GetString("normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User is not active.
        /// </summary>
        internal static string notactive {
            get {
                return ResourceManager.GetString("notactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ounces.
        /// </summary>
        internal static string ounces {
            get {
                return ResourceManager.GetString("ounces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ovum.
        /// </summary>
        internal static string ovum {
            get {
                return ResourceManager.GetString("ovum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to password.
        /// </summary>
        internal static string password {
            get {
                return ResourceManager.GetString("password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password updated.
        /// </summary>
        internal static string passwordupdated {
            get {
                return ResourceManager.GetString("passwordupdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick photo is not supported.
        /// </summary>
        internal static string photoerror {
            get {
                return ResourceManager.GetString("photoerror", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanks for sharing your photos with us!.
        /// </summary>
        internal static string photossharing {
            get {
                return ResourceManager.GetString("photossharing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please.
        /// </summary>
        internal static string please {
            get {
                return ResourceManager.GetString("please", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Points.
        /// </summary>
        internal static string points {
            get {
                return ResourceManager.GetString("points", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Potassium.
        /// </summary>
        internal static string potassium {
            get {
                return ResourceManager.GetString("potassium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pounds.
        /// </summary>
        internal static string pounds {
            get {
                return ResourceManager.GetString("pounds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products.
        /// </summary>
        internal static string products {
            get {
                return ResourceManager.GetString("products", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        internal static string profile {
            get {
                return ResourceManager.GetString("profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile images uploaded.
        /// </summary>
        internal static string profileimages {
            get {
                return ResourceManager.GetString("profileimages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Protein.
        /// </summary>
        internal static string protein {
            get {
                return ResourceManager.GetString("protein", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscription.
        /// </summary>
        internal static string purchases {
            get {
                return ResourceManager.GetString("purchases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity.
        /// </summary>
        internal static string quantity {
            get {
                return ResourceManager.GetString("quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recorded weights.
        /// </summary>
        internal static string recordWeight {
            get {
                return ResourceManager.GetString("recordWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refund.
        /// </summary>
        internal static string refund {
            get {
                return ResourceManager.GetString("refund", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        internal static string register {
            get {
                return ResourceManager.GetString("register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check your email to complete your registration..
        /// </summary>
        internal static string registrationMail {
            get {
                return ResourceManager.GetString("registrationMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remind Me:.
        /// </summary>
        internal static string remind {
            get {
                return ResourceManager.GetString("remind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remind Time:.
        /// </summary>
        internal static string remindTime {
            get {
                return ResourceManager.GetString("remindTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retype PAssword.
        /// </summary>
        internal static string retypePsd {
            get {
                return ResourceManager.GetString("retypePsd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saturated Fats.
        /// </summary>
        internal static string saturatedFats {
            get {
                return ResourceManager.GetString("saturatedFats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string save {
            get {
                return ResourceManager.GetString("save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search by food.
        /// </summary>
        internal static string searchFood {
            get {
                return ResourceManager.GetString("searchFood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        internal static string select {
            get {
                return ResourceManager.GetString("select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select language:.
        /// </summary>
        internal static string selectlang {
            get {
                return ResourceManager.GetString("selectlang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Quantity.
        /// </summary>
        internal static string selectQuantity {
            get {
                return ResourceManager.GetString("selectQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select unit.
        /// </summary>
        internal static string selectunit {
            get {
                return ResourceManager.GetString("selectunit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        internal static string send {
            get {
                return ResourceManager.GetString("send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serving Unit.
        /// </summary>
        internal static string servingUnit {
            get {
                return ResourceManager.GetString("servingUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set up your profile.
        /// </summary>
        internal static string setupProfile {
            get {
                return ResourceManager.GetString("setupProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shop.
        /// </summary>
        internal static string shop {
            get {
                return ResourceManager.GetString("shop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign up.
        /// </summary>
        internal static string signup {
            get {
                return ResourceManager.GetString("signup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skeleton type.
        /// </summary>
        internal static string skeletontype {
            get {
                return ResourceManager.GetString("skeletontype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snack.
        /// </summary>
        internal static string snack {
            get {
                return ResourceManager.GetString("snack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sperm.
        /// </summary>
        internal static string sperm {
            get {
                return ResourceManager.GetString("sperm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your subscription has expired. Do you want to reactivate?.
        /// </summary>
        internal static string subAlert {
            get {
                return ResourceManager.GetString("subAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Days left! Please subscribe.
        /// </summary>
        internal static string subscribe {
            get {
                return ResourceManager.GetString("subscribe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscription.
        /// </summary>
        internal static string subscription {
            get {
                return ResourceManager.GetString("subscription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sugars.
        /// </summary>
        internal static string sugars {
            get {
                return ResourceManager.GetString("sugars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surname.
        /// </summary>
        internal static string surname {
            get {
                return ResourceManager.GetString("surname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please take some time.
        /// </summary>
        internal static string time {
            get {
                return ResourceManager.GetString("time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Under.
        /// </summary>
        internal static string under {
            get {
                return ResourceManager.GetString("under", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsaturated Fats.
        /// </summary>
        internal static string unsaturatedFats {
            get {
                return ResourceManager.GetString("unsaturatedFats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Password.
        /// </summary>
        internal static string updatePsd {
            get {
                return ResourceManager.GetString("updatePsd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload.
        /// </summary>
        internal static string upload {
            get {
                return ResourceManager.GetString("upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot perform this action. Upload process has not finished!.
        /// </summary>
        internal static string uploadaction {
            get {
                return ResourceManager.GetString("uploadaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploading....
        /// </summary>
        internal static string uploading {
            get {
                return ResourceManager.GetString("uploading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User exists.
        /// </summary>
        internal static string userexists {
            get {
                return ResourceManager.GetString("userexists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username - Enter a valid email.
        /// </summary>
        internal static string username {
            get {
                return ResourceManager.GetString("username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User not found.
        /// </summary>
        internal static string usernotfound {
            get {
                return ResourceManager.GetString("usernotfound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valid until:.
        /// </summary>
        internal static string valid {
            get {
                return ResourceManager.GetString("valid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        internal static string warning {
            get {
                return ResourceManager.GetString("warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Water.
        /// </summary>
        internal static string water {
            get {
                return ResourceManager.GetString("water", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to weight.
        /// </summary>
        internal static string weight {
            get {
                return ResourceManager.GetString("weight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weight Date.
        /// </summary>
        internal static string weightDate {
            get {
                return ResourceManager.GetString("weightDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weight type.
        /// </summary>
        internal static string weighttype {
            get {
                return ResourceManager.GetString("weighttype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to Dianet!.
        /// </summary>
        internal static string welcome {
            get {
                return ResourceManager.GetString("welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong credentials.
        /// </summary>
        internal static string wrongcredentials {
            get {
                return ResourceManager.GetString("wrongcredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YES.
        /// </summary>
        internal static string yes {
            get {
                return ResourceManager.GetString("yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Too young to be on diet.
        /// </summary>
        internal static string youngerror {
            get {
                return ResourceManager.GetString("youngerror", resourceCulture);
            }
        }
    }
}
